name: build-release
on:
  workflow_call:
    inputs:
      version_name:
        required: true
        type: string
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version_name }}
          generate_release_notes: true

