name: build-release
on:
  workflow_call:
    secrets:
      EVAN_PAT:
        required: true
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

