name: versioning
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: "ubuntu-latest"
    env:
      isFix: ${{ startsWith(github.event.commits[0].message, 'fix') }}
      isFeat: ${{ startsWith(github.event.commits[0].message, 'feat') }}
      isBreaking: ${{ contains(github.event.commits[0].message, 'BREAKING CHANGE') }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.EVAN_PAT }}
      - name: lint commit message
        if: ${{ env.isFix == 'false' && env.isFeat == 'false' && env.isBreaking == 'false' }}
        run: echo "::warning ::main commits should be specified as fix, feature, or breaking change"
      - name: set github user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: update package.json version
        env:
          VersionLevel: |-
            ${{
              (env.isBreaking == 'true' && 'major') ||
              (env.isFeat == 'true' && 'minor') ||
              'patch'
            }}
        run: yarn version --${{ env.VersionLevel }}
      - name: push bumped version + tags
        run: |
          git push
          git push origin --tags

