name: versioning
on:
  workflow_call:
    inputs:
      scope:
        required: true
        type: string
    secrets:
      PAT:
        required: true
jobs:
  bump-version:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: set github user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: update package.json version
        env:
          VersionLevel: |-
            ${{
              (inputs.scope == 'breaking' && 'major') ||
              (inputs.scope == 'feature' && 'minor') ||
              'patch'
            }}
        run: yarn version --${{ env.VersionLevel }}
      - name: push bumped version + tags
        run: |
          git push
          git push origin --tags

