name: versioning
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: update package.json version
        run: yarn version --patch
        # run: NEW_VERSION=`yarn version --patch | grep "New version" | awk '{printf $4}'`
      - name: push bumped version
        run: git push
